<a href="https://colab.research.google.com/github/Vijay-123-kumar/sorting-/blob/Algorithms/Floyd_Warshall_Algrm_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

def floyd_warshall(graph):
    # Number of vertices
    num_vertices = len(graph)

    # Create a distance matrix initialized to the input graph
    distance = np.array(graph, copy=True)

    # Update the distance matrix with Floyd-Warshall algorithm
    for k in range(num_vertices):
        for i in range(num_vertices):
            for j in range(num_vertices):
                # Update the distance if a shorter path is found
                if distance[i][j] > distance[i][k] + distance[k][j]:
                    distance[i][j] = distance[i][k] + distance[k][j]

    return distance

# Example usage:
# Define a graph with edge weights (use float('inf') for no direct edge)
graph = [
    [0, 3, float('inf'), 7],
    [8, 0, 2, float('inf')],
    [5, float('inf'), 0, 1],
    [2, float('inf'), float('inf'), 0]
]

shortest_paths = floyd_warshall(graph)

print("Shortest path matrix:")
print(shortest_paths)


Shortest path matrix:
[[0. 3. 5. 6.]
 [5. 0. 2. 3.]
 [3. 6. 0. 1.]
 [2. 5. 7. 0.]]
